application_name       = "fleet-portal"
environment_name       = "dev"
primary_region         = "us-west-2"
frontend_image_name    = "frontend-2023.09.39"
frontend_instance_type = "t2.small"
domain_name            = "cloud-stack.io"